name: Artifacts
main: me.sizzlemcgrizzle.artifacts.ArtifactsPlugin
api-version: 1.14
author: sizzlemcgrizzle
version: ${project.version}
depend: [WorldGuard, Blueprints]
permissions:
  artifacts.admin:
    description: admin permission
    default: op
  artifacts.default:
    description: default permission
    default: true
commands:
  artifacts:
    description: Main plugin command group
  setmodeldata:
    description: Changes the custom model data of held item